In [1]:
import numpy as np

# Input features and output labels
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# Normalization
X = X / np.amax(X, axis=0)  # max of each column
y = y / 100  # scaling to 0-1 range

# Sigmoid Activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid
def derivatives_sigmoid(x):
    return x * (1 - x)

# Network configuration
epoch = 5                   # Number of training iterations
lr = 0.1                    # Learning rate
inputlayer_neurons = 2      # Input features
hiddenlayer_neurons = 3     # Neurons in hidden layer
output_neurons = 1          # Output layer neurons

# Weights and biases
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

# Training loop
for i in range(epoch):
    # Forward Propagation
    hinp1 = np.dot(X, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid(hinp)

    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp)

    # Backpropagation
    EO = y - output
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad

    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)  # how much hidden layer weights contributed to error
    d_hiddenlayer = EH * hiddengrad

    # Updating weights and biases
    wout += hlayer_act.T.dot(d_output) * lr
    wh += X.T.dot(d_hiddenlayer) * lr

    # Logs
    print("-----------Epoch", i + 1, "Starts----------")
    print("Input: \n", X)
    print("Actual Output: \n", y)
    print("Predicted Output: \n", output)
    print("-----------Epoch", i + 1, "Ends----------\n")

# Final result
print("Final Input: \n", X)
print("Final Actual Output: \n", y)
print("Final Predicted Output: \n", output)


-----------Epoch 1 Starts----------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.78611388]
 [0.77342109]
 [0.78300563]]
-----------Epoch 1 Ends----------

-----------Epoch 2 Starts----------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.78790091]
 [0.77513354]
 [0.78478427]]
-----------Epoch 2 Ends----------

-----------Epoch 3 Starts----------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.7896391 ]
 [0.77680024]
 [0.78651459]]
-----------Epoch 3 Ends----------

-----------Epoch 4 Starts----------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.79133039]
 [0.77842298]
 [0.78